import type { LocaleKey } from './i18n'

export interface ParticipationLevel {
  /** A0 – A5，以及无法确认时的 A? */
  code: string
  /** 锚点 slug，三语保持一致 */
  slug: string
  /** 用于可视化轨道的填充比例 */
  pct: number
  /** 等级名 */
  name: string
  /** 协议原文定义 */
  definition: string
  /** 极简场景标签（预留） */
  scene?: string
}

/** 跨语言不变的部分。A? 不属于 A0–A5 序列，只用于「无法确认」，
    因此不参与轨道比例（pct 恒为 0）。 */
const BASE = [
  { code: 'A0', slug: 'a0', pct: 0 },
  { code: 'A1', slug: 'a1', pct: 20 },
  { code: 'A2', slug: 'a2', pct: 40 },
  { code: 'A3', slug: 'a3', pct: 60 },
  { code: 'A4', slug: 'a4', pct: 80 },
  { code: 'A5', slug: 'a5', pct: 100 },
  { code: 'A?', slug: 'a-unknown', pct: 0 }
] as const

type LevelText = { name: string; definition: string }

const TEXT: Record<LocaleKey, LevelText[]> = {
  /* ── English ────────────────────────────────────────────── */
  root: [
    {
      name: 'No AI',
      definition:
        'No generative artificial intelligence was used for any substantive creation, editing, or generation of this content.'
    },
    {
      name: 'AI-assisted',
      definition:
        'AI was used mainly for ideation, brainstorming, gathering material, classifying information, analysing problems, or other supporting work; the final content was produced primarily by a human.'
    },
    {
      name: 'AI-edited',
      definition:
        'AI was used for grammar checking, polishing, translation, rewriting, headline optimisation, restructuring, or other editing work, while the main ideas, facts, and core expression came from the human creator.'
    },
    {
      name: 'Partially AI-generated',
      definition:
        'AI directly generated part of the content — for example some sentences, paragraphs, headings, or summaries — after which a human author reviewed, revised, integrated, or rewrote it.'
    },
    {
      name: 'Mostly AI-generated',
      definition:
        'The body of the content was generated by AI, and a human author carried out meaningful review, editing, revision, fact-checking, or restructuring, and takes responsibility for the published result.'
    },
    {
      name: 'AI-generated',
      definition:
        'The content was mainly or entirely generated by AI; a human only made limited selections, arrangements, formatting, or publishing decisions.'
    },
    {
      name: 'Unconfirmed',
      definition:
        'The publisher cannot reasonably establish whether, or how, generative artificial intelligence took part in creating this content. A? describes the limits of what the publisher knows; it is not a level on the A0–A5 scale, and it must not be used to avoid a disclosure that could reasonably be made.'
    }
  ],

  /* ── 简体中文 ───────────────────────────────────────────── */
  zh: [
    {
      name: '未使用 AI',
      definition:
        '在该内容的创作过程中未使用生成式人工智能进行实质性的创作、编辑或内容生成。'
    },
    {
      name: 'AI 辅助',
      definition:
        '人工智能主要用于构思、头脑风暴、资料整理、信息分类、问题分析或其他辅助性工作，最终内容主要由人类独立完成。'
    },
    {
      name: 'AI 编辑',
      definition:
        '人工智能用于语法检查、文字润色、翻译、改写、标题优化、结构调整或其他编辑工作，但内容的主要观点、事实和主体表达由人类创作者提供。'
    },
    {
      name: 'AI 部分生成',
      definition:
        '人工智能直接生成了内容的一部分，例如部分句子、段落、标题、摘要或其他重要内容，随后由人类作者进行审核、修改、整合或重写。'
    },
    {
      name: 'AI 主要生成',
      definition:
        '内容主体由人工智能生成，人类作者对内容进行了具有实质意义的审核、编辑、修改、事实检查或重新组织，并对最终发布内容负责。'
    },
    {
      name: 'AI 生成',
      definition:
        '内容主要或全部由人工智能生成，人类仅进行了有限的选择、整理、格式化或发布处理。'
    },
    {
      name: '未确认',
      definition:
        '发布者无法合理确认生成式人工智能是否参与、或如何参与该内容的创作。A? 描述的是发布者的认知边界，不属于 A0–A5 的参与程度序列，也不应用于回避本可合理作出的披露。'
    }
  ],

  /* ── 繁體中文 ───────────────────────────────────────────── */
  'zh-tw': [
    {
      name: '未使用 AI',
      definition:
        '在該內容的創作過程中未使用生成式人工智能進行實質性的創作、編輯或內容生成。'
    },
    {
      name: 'AI 輔助',
      definition:
        '人工智能主要用於構思、腦力激盪、資料整理、資訊分類、問題分析或其他輔助性工作，最終內容主要由人類獨立完成。'
    },
    {
      name: 'AI 編輯',
      definition:
        '人工智能用於語法檢查、文字潤飾、翻譯、改寫、標題最佳化、結構調整或其他編輯工作，但內容的主要觀點、事實和主體表達由人類創作者提供。'
    },
    {
      name: 'AI 部分生成',
      definition:
        '人工智能直接生成了內容的一部分，例如部分句子、段落、標題、摘要或其他重要內容，隨後由人類作者進行審核、修改、整合或重寫。'
    },
    {
      name: 'AI 主要生成',
      definition:
        '內容主體由人工智能生成，人類作者對內容進行了具有實質意義的審核、編輯、修改、事實查核或重新組織，並對最終發布內容負責。'
    },
    {
      name: 'AI 生成',
      definition:
        '內容主要或全部由人工智能生成，人類僅進行了有限的選擇、整理、格式化或發布處理。'
    },
    {
      name: '未確認',
      definition:
        '發布者無法合理確認生成式人工智能是否參與、或如何參與該內容的創作。A? 描述的是發布者的認知邊界，不屬於 A0–A5 的參與程度序列，也不應用於迴避本可合理作出的披露。'
    }
  ]
}

export function levelsFor(lang: LocaleKey): ParticipationLevel[] {
  const texts = TEXT[lang] ?? TEXT.root
  return BASE.map((base, i) => ({ ...base, ...texts[i] }))
}

/** 兼容旧调用：默认英文 */
export const levels = levelsFor('root')

export const levelByCode = (code: string, lang: LocaleKey = 'root'): ParticipationLevel => {
  const list = levelsFor(lang)
  return list.find((l) => l.code === code) ?? list[0]
}
